### ISSUE TITLE
Remove some unused text

### ISSUE THREAD

**Issue by ray1997** [EdiWang/Character-Map-UWP#107]
This is not that much important, but there are some texts that unused or obsolete.

Here is an excel sheet on text resource usage: 
[AllTextLocation.xlsx](https://github.com/EdiWang/Character-Map-UWP/files/4550262/AllTextLocation.xlsx)

TBH, it can stay as it has no performance impact on application whatsoever.
It would only annoy new translator who try to translate the app and have to translate some text multiple times or waste time on unused text.
Overall, there's only 45 of them that unused.

Here are all those 45 unused texts:
Name | Value 
------------ | -------------
BtnCopy.Text | Copy as text
BtnSavePng.Text | Save as PNG
BtnSaveSvg.Text | Save as SVG (monochrome only)
BtnSaveSvgRaw.Text | Save as SVG
BtnSelect.Content | Select
BtnShowPane.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip | Show font pane
BtnViewCollection.Content | View Collection
BtnXAMLGeometry.Content | Click to view
CbCharacterLabel.Header | Character Label
CbiPageOrientationLandscape.Content | Landscape
CbiPageOrientationPortrait.Content | Portrait
CbListStyle.Header | List Style
CbShowMargins.Content | Show margins
CharacterKeystrokeLabel | Keystroke: Alt + {0:0000}
CharacterSavedMessage.Text | Saved to
CharsLabel.Text | Char(s)
ChkBxHideWhitespace.Content | Hide whitespace and control characters
ChkBxShowBorders.Content | Show borders
ColoredGlyphLabel.Text | Colored Glyph
ColorGlyphToggle.OffContent | Monochrome glyphs
ColorGlyphToggle.OnContent | Color glyphs
CreateCollectionEntryBox.Header | Collection Name
DeleteCollectionButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip | Delete Collection
DigCreateCollection.PrimaryButtonText | Create
DigCreateCollection.SecondaryButtonText | Cancel
DigCreateCollection.Title | Create Collection
DigDeleteCollection.PrimaryButtonText | Delete
DigDeleteCollection.SecondaryButtonText | Cancel
DigDeleteCollection.Title | Are you sure you want to delete this collection?
DigRenameCollection.PrimaryButtonText | Rename
DigRenameCollection.SecondaryButtonText | Cancel
DigRenameCollection.Title | Rename Collection
DigSettings.PrimaryButtonText | OK
DigSettings.Title | Settings
DlgDeleteFont.Title | Are you sure you want to delete this font from your library?
DlgException.PrimaryButtonText | OK
DlgException.Title | Something went wrong
DlgExceptionCopyMessage.Text | Copy error to Clipboard and open GitHub
DlgExceptionExpander.Header | View Full Exception details
DlgExceptionMessage.Text | To help us debug and fix this for you, please consider opening an issue on our GitHub page and posting the details. We'll try and fix it right away!
DWriteSourceAppxPackage | Microsoft Store
DWriteSourcePerMachine | All Users
DWriteSourcePerUser | Current User only
DWriteSourceRemoteFontProvider | Cloud Provider
DWriteSourceUnknown | Undefined
ExportPNGLabel.Text | Save as PNG Image
ExportSVGGlyphLabel.Text | SVG Glyph
ExportSVGLabel.Text | Save as SVG Image
FilePickerConfirm | Import
FilterAllFonts.Content | All Fonts
FilterImportedFonts.Content | Imported Fonts
FilterSymbolFonts.Content | Symbol Fonts
FontDisplayHeader.Text | Font Display Options
FontListDisplayHeader.Text | Fonts List Display
FontListDisplayToggle.OffContent | Show Font names using System default font
FontListDisplayToggle.OnContent | Show Font names using actual font
FontListFilter.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip | Filter fonts
FontOptionsButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip | Font Rendering Options
FontPropCharCount.Text | Character Count
FontPropCount.Text | Glyph Count
FontPropertiesButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip | Font Face Properties
FontPropFace.Text | Face Name
FontPropFamily.Text | Family Name
FontPropFilePath.Text | File Path
FontPropFileSize.Text | File Size
FontPropInstallType.Text | Install Type
FontPropMonospaced.Text | Is Monospaced
FontPropStretch.Text | Stretch
FontPropStyle.Text | Style
FontPropSymbol.Text | Is Symbol Font
FontPropTitle.Text | Font Face Properties
FontPropType.Text | Type
FontPropWeight.Text | Weight
FontPropXaml.Text | XAML FontFamily Source
FontsClearedOnNextLaunchNotice | Some fonts could not be completely removed right now. These fonts will not show in the application and will be completely removed next time the app is launched.
FontsCountLabel.Text | Fonts
GlyphAnnotation_None | None
GlyphAnnotation_UnicodeHex | Unicode Hex
GlyphAnnotation_UnicodeIndex | Unicode Index
GridSlider.Header | Character Grid Size
ImportFileCopyFail | Something went wrong. Please try again later.
ImportFontHelpBlock.Text | Drag fonts into the app to copy them to your library.
ImportFontsButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip | Import Fonts
ImportNotAFile | Not a file
ImportPendingDelete | Existing font pending delete. Please restart app.
ImportUnavailableFile | File not available
ImportUnsupportedFileType | Unsupported File Type
ImportUnsupportedFontType | Unsupported Font Type
InstallTypeImported | Not Installed (Imported)
InstantSearchToggle.OffContent | Instant search disabled
InstantSearchToggle.OnContent | Instant search enabled
InstantSearchToggleHeader.Text | Instant Search
InvalidFontMessage | Sorry, we couldn't find any supported font data in this file.
InvalidFontTitle | Unsupported File
LoadingFontListError | Error Loading Font List
NewCollectionItem.Text | New Collection
NoticeLabel.Text | Notice
NotificationAddedToCollection | {0} was added to "{1}" collection
NotificationCollectionDeleted | {0} collection deleted
NotificationFontAddedBody.Text | was added to
NotificationFontRemovedBody.Text | was removed from
NotificationImportFailed | Import Failed
NotificationMultipleFontsAdded | {0} files were added to your collection
NotificationSingleFontAdded | {0} was added to your collection
OpenFontButton.[using:Windows.UI.Xaml.Controls]ToolTipService.ToolTip | Open Font
OpenFontPickerConfirm | Open
OpenInNewWindow.Text | Open in New Window
OptionAllFonts.Text | All Fonts
OptionAppxFonts.Text | From Microsoft Store
OptionCloudFonts.Text | Cloud-based Fonts
OptionColorFonts.Text | Color Fonts
OptionDecorativeFonts.Text | Decorative Fonts
OptionImportedFonts.Text | Imported Fonts
OptionMonospacedFonts.Text | Monospaced Fonts
OptionMoreFilters.Text | More
OptionSansSerifFonts.Text | Sans Serif Fonts
OptionScriptFonts.Text | Script Fonts
OptionSerifFonts.Text | Serif Fonts
OptionSymbolFonts.Text | Symbol Fonts
PngSlider.Header | PNG Resolution (pixel)
PrintCharacterFilterContent.Text | Choose character groups to display
PrintDataHeader.Text | Data
PrintLayout_Grid | Grid
PrintLayout_List | List
PrintLayout_TwoColumn | Two Columns

**Comment by JohnnyWestlake** [comment]
(I think that table is a bit incorrect compared to the spreadsheet?)

Thanks for looking through these! Some of those are defo in use but have their keys dynamically generated (mostly enums or notifications)
- PrintLayout_{0} 
- Option{0}Fonts.Text
- Notification{0}
- GlyphAnnotation_{0}
- DWriteSource{0}

And a few will be brought back into the UI quite soon, but the ones I reckon can ideally dropped are:
- CharsLabel.Text
- DigSettings.{0}
- Filter{0}Fonts.Content
- FontListDisplayToggle.{0}
- FontCountsLabel.Text
- GridSlider.Header
- PngSlider.Header
- SettingsLangOverride.{0}
- BtnSavePng.Text
- BtnSaveSvg.Text
- BtnSaveSvgRaw.Text
- DigRenameCollection.SecondaryButtonText
- SettingsUnicodeDescription.Text
- SettingsUnicodeHeader.Text
- WeightSelector.Header 

I'll be adding in a number of new resources with my next commit (on AdvancedSettings branch) so I can trim them then, otherwise please feel free to open  pull request (:

**Comment by ray1997** [comment]
The table I only select a text that has "Number of occurrence" less than 1, but I'm sure there bound to be some mistake as I'm manually select row of text afterward :/

I'll send in a pull request removing those text now.
