### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by brullsker** [EdiWang/Character-Map-UWP#12]
I've done a Russian translation and would like to send you the ru-RU resources file with this.

[ru-RU.zip](https://github.com/EdiWang/UWP-CharacterMap/files/1191692/ru-RU.zip)

**Comment by wstaelens** [comment]
TIP: use the Microsoft MAT tool for translations
https://developer.microsoft.com/en-us/windows/develop/multilingual-app-toolkit  😉

**Comment by brullsker** [comment]
For MAT, i need .xlf files. It doesn't work with .resw files.

**Comment by wstaelens** [comment]
@brullsker: add it to the uservoice site (i'll upvote).
https://multilingualapptoolkit.uservoice.com/ 

because sharing .xlf files would be way more easier to do translations and maintaining them.

**Comment by ray1997** [comment]
This issue is 3 years old and the text that translate in there (ru-RU.zip) was already obsolete. Maybe it's time to close this issue? @EdiWang @JohnnyWestlake

**Comment by EdiWang** [comment]
Closing this issue as inactive. 

We can't trust machine translations either. It's better to have a human contributor for each of the language file. Otherwise I would like to just remove the outdated language file(s).
