### ISSUE TITLE
Fonts not in alphabetical order

### ISSUE THREAD

**Issue by JoeUX** [EdiWang/Character-Map-UWP#16]
I think the font listing (left-hand column) is supposed to be in alphabetical order, since it has A, B, C, etc. but the fonts within some of the letters are not listed alphabetically. For example, look at C: Corbel, Cooper, and lots of others come before Calibri, which is almost last in that section. It's harder to find specific fonts when they're not in alphabetical order.

**Comment by EdiWang** [comment]
Hi, @JoeUX 

Thank you! It's a very good suggesstion. I will put this into next release soon!

**Comment by EdiWang** [comment]
@JoeUX New version will release within 24 hours.

**Comment by JoeUX** [comment]
Thanks! It came through today on my machine. Looks good.

**Comment by CathyOTR** [comment]
I love this character map but mine doesn't show up I alphabetical order either. Do I need to do anything to update to the new version? I have opened and used it many times since the new release that is mentioned here. Thanks so much!
