### ISSUE TITLE
PNG Exports are cut off at the bottom

### ISSUE THREAD

**Issue by domcote** [EdiWang/Character-Map-UWP#20]
![charactermap_20180313170240](https://user-images.githubusercontent.com/37335619/37353793-5e4de014-26e0-11e8-8b8e-e55279524ff0.png)
![charactermap_20180313170625](https://user-images.githubusercontent.com/37335619/37354003-e7dd19e4-26e0-11e8-9e9d-6b6d8b49cfa7.png)
Here are some PNGs exported from Version 2018.1.1.0. Not sure why this is happening, never did before. New device? I have a Surface Book 2, so super high DPI. Not all fonts seem equally impacted. Very obvious though on Segoe UI Symbol.

**Comment by EdiWang** [comment]
Confirmed as a bug
