### ISSUE TITLE
Ability to add Glyphs to collections

### ISSUE THREAD

**Issue by TheJoeFin** [EdiWang/Character-Map-UWP#24]
When using Character-Map for development it would be nice to be able to make collections of the different Glyphs to make it fast and easy to go to a self made collection of glyphs which were organized for a purpose.

**Comment by geometrikal** [comment]
I'd like this feature too. Even just a simple favouriting of the glyphs.

**Comment by EdiWang** [comment]
Related PR #59

**Comment by EdiWang** [comment]
Microsoft Store is preventing apps that using Microsoft.UI.Xaml >= 2.3.200213001 from validation. I'll close this issue for now since the code is merged into master. After the store issue is fixed from Microsoft we can download a new version of this App.
