### ISSUE TITLE
Display Hex Code and Unicode Name

### ISSUE THREAD

**Issue by Bolpat** [EdiWang/Character-Map-UWP#25]
Display the hex code and Unicode name somewhere below the character. If space is an issue, for XAML Code, FontIcon and Symbol Icon, it suffices to have a copy button. There is no need to display what exactly is being copied. The same for saving the glyph as PNG. Most users don't need these ever.

**Comment by EdiWang** [comment]
According to my user reports, the XAML code and export as PNG capabilities are both being highly used, they can't be easily changed, but I got your point, I will see how these can be improved on the UI side.
