### ISSUE TITLE
Instant Search

### ISSUE THREAD

**Issue by Bolpat** [EdiWang/Character-Map-UWP#27]
Instant search is nice, but only if it is super fast. If it isn't – like on my machine –, make it possible to disable it.

**Comment by JohnnyWestlake** [comment]
Whilst this is still open, I'd like to give this another look at and move the search options into the settings dialog for UX / UI reasons (as well as to avoid accessibility issues the current implementation causes)

**Comment by JohnnyWestlake** [comment]
#71 will address this
