### ISSUE TITLE
[WIP]UI issues since version 2018.5.0.0

### ISSUE THREAD

**Issue by TheGaladras** [EdiWang/Character-Map-UWP#32]
![cmuwp](https://user-images.githubusercontent.com/8669826/48121555-8d089100-e275-11e8-9cd7-83f1ce198914.png)

The new version 2018.5.0.0 arrived a few minutes ago and I recognized that the new update seems to have some issues with the design. Did you remove the fluent design? I´m on 1809 with the latest drivers etc. installed (AMD in my case) and no other app behaves like this.

**Comment by EdiWang** [comment]
@TheGaladras yes I did remove the FDS in this release. Are you using dark theme in Windows Settings?

**Comment by TheGaladras** [comment]
Yes, I'm using the dark theme. No problem with removing the fluent design, but it should remain readable. ;)

**Comment by TheGaladras** [comment]
Thanks.

**Comment by EdiWang** [comment]
Fixed in v2018.5.1
