### ISSUE TITLE
Save as SVG Feature

### ISSUE THREAD

**Issue by PhanindraNath** [EdiWang/Character-Map-UWP#33]
Along with PNG, Save As SVG feature would be great

**Comment by JohnnyWestlake** [comment]
A bit late on this, but if these two caveats are acceptable:

- You'll only be able to save the monochrome versions of glyphs, not their multi-coloured variants (for most users this will only affect emoji fonts)
- Probably won't work for bitmap fonts but I've yet to test. (But it's a bit pointless anyway in that case)

then I've just pushed a change that does this on my fork, and will look to merging it back here soon.

**Comment by EdiWang** [comment]
Thanks @JohnnyWestlake

**Comment by EdiWang** [comment]
Fixed in #38
