### ISSUE TITLE
Preview Font File Feature

### ISSUE THREAD

**Issue by JohnnyWestlake** [EdiWang/Character-Map-UWP#34]
Feature request: Ability to preview a non-installed font file.

Either via drag and drop onto the main window, and application registered as a Font File handler. This will help replace the default and pretty useless Windows Font preview feature.

My initial idea for both is that it would spawn a separate window that does not have the left most column, but only the right and central columns for the selected font.

I did try to implement myself but it wasn't exactly straight forward to allow separate windowing with the app in it's current architecture and I didn't want to open a pull request that pretty much changed everything D; That, and DirectWrite via SharpDX aren't exactly friendly to opening a font via a file.

**Comment by EdiWang** [comment]
@JohnnyWestlake 

Thanks for your suggesstion. There do have technical difficulties to implement this feature. Current design is based on installed fonts only. 

I need to do some research on how to do this.

**Comment by JohnnyWestlake** [comment]
@EdiWang I will say this is a lot easier when using Win2D over SharpDX, where you can pass a file URI into the CanvasFontSet constructor and load the font (which requires copying the font in to the apps temporary storage first)

**Comment by JohnnyWestlake** [comment]
I've actually done this now on my fork, along with adding font information, and ability too switch between color and mono glyphs and switching between the different font faces in a family - I may open a fork after I've cleaned up the export to not crop characters (which can be done by implementing ICanvasTextRender which will give you the final draw bounds of a glyph)

**Comment by EdiWang** [comment]
Hi @JohnnyWestlake 

Thanks! I am very interested in your enhancement for this project. Please feel free to open a PR.

**Comment by EdiWang** [comment]
Addressed via #38
