### ISSUE TITLE
Error Loading Font List

### ISSUE THREAD

**Issue by niamvh** [EdiWang/Character-Map-UWP#42]
I am not able to find a solution for my issue so I'm posting it here. I downloaded your free Character Map UWP app from the MS store for my Windows 10 laptop. I launch the application and I get the error: Error Loading Font List  Index and length must refer to a location within the string.  Parameter name: length

Please advise on how to fix this. I like your app over the other apps available.

![ErrorLoadingFontList](https://user-images.githubusercontent.com/49216332/55445266-236c8480-5580-11e9-9cd2-4b2230fd9bfe.JPG)

**Comment by JohnnyWestlake** [comment]
Well, this is my fault so I apologise for that.

It is this particular line that directly throws the exception:
```var list = AlphaKeyGroup<InstalledFont>.CreateGroups(FontList, f => f.Name.Substring(0, 1));```
which means for some reason, one or more of your fonts are not being assigned a name correctly (and clearly they used too if you were previously using the app.)

Hopefully will push a fix up later today.

Out of curiosity, what language /locale is your Windows set to?

**Comment by niamvh** [comment]
I take it an update will be released for the app to fix this bug?

**Comment by EdiWang** [comment]
@niamvh Version 2019.3.3 is submitted to the store, it is currently under Microsoft certification, you may get the update in a few hours or a few days.

**Comment by niamvh** [comment]
Thank you very much!
