### ISSUE TITLE
Add ability to print the font glyph

### ISSUE THREAD

**Issue by ray1997** [EdiWang/Character-Map-UWP#46]
Like in Font Creator where you can print all the glyph into a PDF document of font sheet.

If you would implement it and look for button placement. Maybe add a print button next to "Font display option" with a list of menu items

* Print all glyph to a text file
* Print all glyph to PDF
* Print all glyph as one picture
* Print all glyph as pictures to a folder

etc.

**Comment by JohnnyWestlake** [comment]
Currently tracked in [/Character-Map-UWP/tree/Printing](https://github.com/EdiWang/Character-Map-UWP/tree/Printing)

**Comment by JohnnyWestlake** [comment]
This is a bit frustrating to do in UWP as you have to present the pages up-front to the printing API as ready-to-go FrameworkElements, which when you want to print 200 pages results in crashing with nothing we can do about it.

Going to have to limit it to 50 or so pages at a time and stick some awkward UI around it.

**Comment by ray1997** [comment]
The feature work for now, so I'll close this issue.
