### ISSUE TITLE
Search Exception

### ISSUE THREAD

**Issue by hippieZhou** [EdiWang/Character-Map-UWP#51]
![image](https://user-images.githubusercontent.com/13598361/58392110-fd88cb00-806a-11e9-83d4-21b8b51fd710.png)

**Comment by JohnnyWestlake** [comment]
I kept telling myself to remember to escape the SQL strings... :'(

**Comment by hippieZhou** [comment]
in some way. sql strings can improve app's performance, but you had batter to make it in your control first.
