### ISSUE TITLE
Feature Proposal: Add symbol enum constant references to Segoe MDL2 Assets

### ISSUE THREAD

**Issue by kmgallahan** [EdiWang/Character-Map-UWP#56]
The [Symbol Enum](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.symbol) "Defines constants that specify a glyph from the Segoe MDL2 Assets font to use as the content of a SymbolIcon."

It would be helpful when browsing the Segoe MDL2 Assets to see the short name for icons when one is available to use. It could appear over in the bottom right with the other items (XAML Code, Font Icon, Symbol Icon).

**Comment by JohnnyWestlake** [comment]
Now live on the store release

**Comment by kmgallahan** [comment]
Awesome, thanks!

One issue though, or unexpected behavior anyways - as mentioned:

> It would be helpful when browsing the Segoe MDL2 Assets to see the short name for icons **when one is available to use**.

Currently this is showing for every font, and every icon:

![Annotation 2020-02-22 172312](https://user-images.githubusercontent.com/5379488/75100138-083fa480-5598-11ea-9392-9e19f3a17419.png)

Where the expected/desired behavior would be that that part of the UI would have its visibility bound to whether or not it has an entry in the Symbol Enum (so it would only be showing for a subset of the Segoe MDL2 Assets font icons).

**Comment by JohnnyWestlake** [comment]
#71 will take care of that
