### ISSUE TITLE
Error loading Font List

### ISSUE THREAD

**Issue by Avidin** [EdiWang/Character-Map-UWP#74]
New Update create error on each font Windows 1909 (Build18363.657)

![grafik](https://user-images.githubusercontent.com/4540471/75972644-0b119200-5ed4-11ea-9e44-e19569fc1fe3.png)

**Comment by JohnnyWestlake** [comment]
@Avidin Thanks, and sorry about this! Submitted a pull request that fixes this.

(Also slightly irks me that I replaced the error dialog everywhere in the app with one that provides error details for GitHub, apart from this one place 😅)

**Comment by EdiWang** [comment]
Version 2020.5.2 is released to store to fix this issue
