### ISSUE TITLE
Can not set Character Map UWP as a default app to open .ttf file

### ISSUE THREAD

**Issue by WolfLee-red** [EdiWang/Character-Map-UWP#83]
应用似乎没有关联 .ttf 文件。「设置」中只能将其设置成 .otc、.otf、.ttc 文件的默认打开应用。

**Comment by JohnnyWestlake** [comment]
Unfortunately Microsoft prevents *any* application from legally being set as the default app to open ttf files =[

As an aside, I've also considered removing the default file associations entirely as it has the side effect of prevent you from easily being able to install fonts from Windows Explorer, as it no longer shows the install buttons and prompts if you choose a default app for font files that isn't the Windows font viewer, and we can't install fonts from a UWP app without breaking outside the sandbox

**Comment by EdiWang** [comment]
Due to Windows system limitation, closing this issue as won't fix
