### ISSUE TITLE
When Transparency Effects is disabled, Settings View becomes unreadable

### ISSUE THREAD

**Issue by Lemmingh** [EdiWang/Character-Map-UWP#87]
## Steps to repro

1. Go to **Windows Settings** > **Personalization** > **Colors**. Turn *off* **Transparency effects**.
2. Open **Character Map UWP**. Go to **Settings**.
3. It appears terrible.

## Environment

* **OS Version**: `10.0.18363.657`
* **OS Architecture**: `X64`
* **App Version**: `2020.6.0.0`
* **App Culture**: `zh-CN`

## A possible solution

In `SettingsView.xaml`, there is currently

```xaml
<Grid.Background>
    <AcrylicBrush
        win1903:TintLuminosityOpacity="0.2"
        BackgroundSource="Backdrop"
        TintColor="{ThemeResource SystemChromeGrayColor}"
        TintOpacity="0.5" />
</Grid.Background>
```

The `AcrylicBrush` lacks `FallbackColor`, which should be the cause of the issue.

Setting a proper FallbackColor, probably `Gainsboro` in Light mode and `#FF2C2C2C` in Dark mode, might help.

**Comment by JohnnyWestlake** [comment]
Thanks for reporting @Lemmingh , I've addressed this as part of #85
