### ISSUE TITLE
Fonts not loading in version 2020.7.0

### ISSUE THREAD

**Issue by EdiWang** [EdiWang/Character-Map-UWP#89]
From a direct email from user:

I am having a really hard time with the Character Map UWP, when opening it continues to say “loading fonts” and will not open. I’ve exited, and opened again. I’ve restarted the program. I’ve uninstalled, restarted my computer and then installed it back. Nothing. 

It continues to show me this: 

![image](https://user-images.githubusercontent.com/3304703/76696651-c7373d80-66c8-11ea-8841-c1a96ffa59de.png)

I really do love using Character Map, I use it for work. So i’m really anxious to have this working again. Please help!

**Comment by EdiWang** [comment]
This issue seems to be introduced in #86 

CC @JohnnyWestlake

**Comment by JohnnyWestlake** [comment]
Will take a look in a few hours... Might have something to do with the TitleBar so I'll manually throw a few exceptions in there and see what happens

**Comment by JohnnyWestlake** [comment]
A little stuck on this one, I can't ever get it into this state. Any C++ error tends to terminate the app entirely with no warning, so it's not that. And C# errror during startup shows the exception dialog from my tests

**Comment by EdiWang** [comment]
It's not a single case, there are a few users suggesting the same thing in feedback.

![image](https://user-images.githubusercontent.com/3304703/76702036-81e33200-6701-11ea-8e64-6a8849002bdf.png)

**Comment by EdiWang** [comment]
I can't reproduce the issue on 3 of my machines with Windows 10 v1909 - 2004, existing upgrade and new installs are all good. It's wired. @JohnnyWestlake

**Comment by EdiWang** [comment]
@JohnnyWestlake 

From the screenshot, I guess the font is actually loaded because the font name is showing in the title bar as "A little sunshine", but the loading animation didn't dismiss. 

An ugly and violent workaround is to force dismiss the animation after ```TitlePrefix``` is updated in ```XamlTitleBar```, but since I can't reproduce the issue, I don't have much confidence to write such a workaround, we haven't found the root cause yet.

**Comment by JohnnyWestlake** [comment]
My 1809 machine seems to have updated itself to 1903 so I can't double check that.

It's strange as the LoadingRoot is visible with `x:Load`, so if the `ViewModel.IsLoadingFonts` is set to false it is literally removed from the VisualTree.

But if it does not get set to false, the error dialog should show up 😐

**Comment by JohnnyWestlake** [comment]
Boom, hello. So I've got an ancient tablet that I found in a closet that's running 1809 and exhibits this problem - I'll stick debugger on it and let you know

**Comment by EdiWang** [comment]
Version 2020.8.2 has submitted to Microsoft yesterday, but the Store certification is taking longer than usual. This issue may last a couple more days before updates are rolling out.

**Comment by EdiWang** [comment]
Version 2020.8.2 passed verification and rolling out now.
