### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by SimoneRaspagni** [EdiWang/Character-Map-UWP#99]
Hello!
I have made a Italian translation and would like to send you the it-IT resource file. (.xlf)
Thanks
[it-IT.zip](https://github.com/EdiWang/Character-Map-UWP/files/4471286/it-IT.zip)

**Comment by JohnnyWestlake** [comment]
thanks @SimoneRaspagni! @EdiWang has merged this now thanks to Ray, so it should be on the store for you now / very soon!
